/*
SELECT * FROM ALT_RULE WHERE ROWNUM < 10
SELECT * FROM ALT_RULE WHERE ALT_QUERY_FK = 415

SELECT * FROM ALT_QUERY WHERE ROWNUM < 10
SELECT * FROM ALT_QUERY WHERE CATEGORY_FK = 121

SELECT * FROM ALT_QUERY_CATEGORY WHERE ROWNUM < 10


INSERT INTO ALT_QUERY(DESCR, NAME, QUERY) 
VALUES('Automation purposes', 'Automation_Test', 'Test', 121);

--Automation purposes	Automation_Test	Test	121
*/

SELECT DISTINCT USERNAME FROM SYS.DBA_USERS
ORDER BY USERNAME

SELECT DISTINCT TABLE_NAME, COLUMN_NAME, DATA_TYPE FROM SYS.USER_TAB_COLUMNS
ORDER BY COLUMN_NAME

SELECT DISTINCT COLUMN_NAME, TABLE_NAME, OWNER FROM ALL_TAB_COLUMNS
WHERE COLUMN_NAME LIKE '%TITLE%'
ORDER BY COLUMN_NAME

SELECT COUNT(*) FROM (
SELECT DISTINCT COLUMN_NAME, TABLE_NAME, OWNER SCHEMA_NAME FROM ALL_TAB_COLUMNS
--WHERE COLUMN_NAME LIKE '%HEADER%'
--ORDER BY COLUMN_NAME, TABLE_NAME, SCHEMA_NAME 
) T

SELECT DISTINCT COLUMN_NAME FROM ALL_TAB_COLUMNS
WHERE COLUMN_NAME LIKE '%HEADER%'
ORDER BY COLUMN_NAME

SELECT * FROM CDM_L10.PRINTOUT_FIELD_ORDER

SELECT DISTINCT COLUMN_NAME, TABLE_NAME FROM USER_TAB_COLUMNS
WHERE COLUMN_NAME LIKE '%PAGE%'
ORDER BY COLUMN_NAME

SELECT DISTINCT D.USERNAME SCHEMA_NAME,A.OBJECT_TYPE,A.OBJECT_NAME TABLE_NAME FROM SYS.DBA_USERS D, ALL_OBJECTS A
WHERE 
A.OBJECT_TYPE = 'TABLE'
AND D.USERNAME = A.OWNER
ORDER BY SCHEMA_NAME, TABLE_NAME

LOTOSDB.MESSAGE

LOTOSFI.CMS_VAL_TYPE
LOTOSFI.CMS_PROFILE
LOTOSFI.EAN_PRODUCTS
LOTOSFI.EMAIL_RECIPIENT

SELECT * FROM LOTOSFI.RET_USR
SELECT * FROM LOTOSFI.RET_USR_TYPES
SELECT * FROM LOTOSFI.USR

SELECT * FROM LOTOSRI.PGM_LAYOUT
SELECT * FROM LOTOSRI.PGM_LOOKUP
SELECT * FROM LOTOSRI.PGM

SELECT * FROM LOTOSRI.USR_TYPE

SELECT DISTINCT OWNER,OBJECT_TYPE, OBJECT_NAME  FROM ALL_OBJECTS
WHERE OBJECT_TYPE = 'TABLE'
AND OBJECT_NAME LIKE '%CMS%'


SELECT DISTINCT OWNER,OBJECT_TYPE, OBJECT_NAME  FROM ALL_OBJECTS
WHERE OBJECT_TYPE = 'TABLE'
AND OBJECT_NAME LIKE '%CMS%'

SELECT DISTINCT OWNER,OBJECT_TYPE, OBJECT_NAME  FROM ALL_OBJECTS
WHERE OBJECT_TYPE = 'TABLE'
AND OBJECT_NAME LIKE '%MSG%'
--AND OWNER IN ('LOTOSFI')
ORDER BY OBJECT_NAME

SELECT * FROM LOTOSRI.USR
--WHERE lower(USR_NM) like '%delgio%'
ORDER BY USR_NM

SELECT * FROM LOTOSFI.EMAIL_MSG
SELECT * FROM LOTOSFI.USR_MSG

SELECT * FROM LOTOSRI.USR_MSG
SELECT * FROM LOTOSRI.USR_MSG_PRIORITY
